In [1]:
!pip install opencv-python==4.1.2.30

In [2]:
!pip install tensorflow==1.14.0

In [3]:

# It loads the classifier uses it to perform object detection on a webcam feed.
# It draws boxes and scores around the objects of interest in each frame from
# the webcam.

# Import packages
import os
import cv2
import numpy as np
import tensorflow as tf
import sys
from utils import label_map_util
from utils import visualization_utils as vis_util

In [4]:
detection_graph = tf.Graph()


# Import utilites
# from utils import label_map_util

# Name of the directory containing the object detection module we're using
TRAINED_MODEL_DIR = 'frozen_graphs'

# Path to frozen detection graph .pb file, which contains the model that is used
# for object detection.
PATH_TO_CKPT = TRAINED_MODEL_DIR + '/frozen_inference_graph.pb'
print(PATH_TO_CKPT)
# Path to label map file
PATH_TO_LABELS = TRAINED_MODEL_DIR + '/labelmap.pbtxt'

frozen_graphs/frozen_inference_graph.pb


In [5]:
# Number of classes the object detector can identify
NUM_CLASSES = 2

label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
categories = label_map_util.convert_label_map_to_categories(
    label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
category_index = label_map_util.create_category_index(categories)

print(category_index)

W0613 12:56:54.909733 24616 deprecation_wrapper.py:119] From C:\Users\ragav\OneDrive\Pictures\discussion\face_\utils\label_map_util.py:132: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.



{1: {'id': 1, 'name': 'with_mask'}, 2: {'id': 2, 'name': 'without_mask'}}


In [6]:
print("> ====== Loading frozen graph into memory")
detection_graph = tf.Graph()
with detection_graph.as_default():
    od_graph_def = tf.GraphDef()
    with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
        serialized_graph = fid.read()
        od_graph_def.ParseFromString(serialized_graph)
        tf.import_graph_def(od_graph_def, name='')

    sess = tf.Session(graph=detection_graph)
    print(">  ====== Inference graph loaded.")

> ====== Loading frozen graph into memory
>  ====== Inference graph loaded.


In [7]:
# Input tensor is the image
image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')


# Output tensors are the detection boxes, scores, and classes
# Each box represents a part of the image where a particular object was detected
detection_boxes = detection_graph.get_tensor_by_name('detection_boxes:0')

# Each score represents level of confidence for each of the objects.
# The score is shown on the result image, together with the class label.
detection_scores = detection_graph.get_tensor_by_name('detection_scores:0')
detection_classes = detection_graph.get_tensor_by_name('detection_classes:0')

# Number of objects detected
num_detections = detection_graph.get_tensor_by_name('num_detections:0')


In [8]:
print(image_tensor)

Tensor("image_tensor:0", shape=(?, ?, ?, 3), dtype=uint8)


In [9]:
detection_boxes

<tf.Tensor 'detection_boxes:0' shape=<unknown> dtype=float32>

In [110]:
image = cv2.imread('image3.jpg')
image = cv2.resize(image, (1080, 1080))
image_expanded = np.expand_dims(image, axis=0)
print(image.size)
print(image.shape)

3499200
(1080, 1080, 3)


In [111]:
(boxes, scores, classes, num) = sess.run(
            [detection_boxes, detection_scores, detection_classes, num_detections],
            feed_dict={image_tensor: image_expanded})

In [119]:
c = classes.flatten()

In [120]:
c

array([1., 1., 1., 1., 2., 2., 2., 2., 1., 2., 2., 1., 1., 2., 2., 1., 2.,
       1., 1., 2., 1., 2., 2., 1., 2., 2., 2., 2., 2., 2., 1., 2., 1., 2.,
       1., 1., 2., 2., 2., 2., 2., 2., 2., 1., 1., 2., 2., 2., 1., 1., 1.,
       2., 1., 2., 2., 1., 1., 2., 1., 2., 2., 1., 2., 2., 1., 2., 2., 2.,
       1., 2., 2., 1., 2., 1., 2., 2., 2., 1., 1., 1., 2., 2., 2., 1., 1.,
       2., 1., 1., 1., 1., 1., 2., 1., 2., 1., 1., 1., 2., 2., 1., 2., 2.,
       1., 1., 1., 1., 2., 2., 1., 2., 1., 1., 1., 2., 2., 1., 2., 1., 1.,
       2., 1., 2., 2., 2., 2., 2., 1., 2., 2., 2., 2., 2., 2., 2., 1., 2.,
       1., 2., 1., 2., 2., 2., 1., 2., 2., 1., 2., 2., 2., 2., 1., 2., 2.,
       2., 2., 2., 1., 2., 1., 2., 2., 1., 1., 2., 2., 2., 1., 2., 2., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [121]:
c

array([1., 1., 1., 1., 2., 2., 2., 2., 1., 2., 2., 1., 1., 2., 2., 1., 2.,
       1., 1., 2., 1., 2., 2., 1., 2., 2., 2., 2., 2., 2., 1., 2., 1., 2.,
       1., 1., 2., 2., 2., 2., 2., 2., 2., 1., 1., 2., 2., 2., 1., 1., 1.,
       2., 1., 2., 2., 1., 1., 2., 1., 2., 2., 1., 2., 2., 1., 2., 2., 2.,
       1., 2., 2., 1., 2., 1., 2., 2., 2., 1., 1., 1., 2., 2., 2., 1., 1.,
       2., 1., 1., 1., 1., 1., 2., 1., 2., 1., 1., 1., 2., 2., 1., 2., 2.,
       1., 1., 1., 1., 2., 2., 1., 2., 1., 1., 1., 2., 2., 1., 2., 1., 1.,
       2., 1., 2., 2., 2., 2., 2., 1., 2., 2., 2., 2., 2., 2., 2., 1., 2.,
       1., 2., 1., 2., 2., 2., 1., 2., 2., 1., 2., 2., 2., 2., 1., 2., 2.,
       2., 2., 2., 1., 2., 1., 2., 2., 1., 1., 2., 2., 2., 1., 2., 2., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [114]:
category_index

{1: {'id': 1, 'name': 'with_mask'}, 2: {'id': 2, 'name': 'without_mask'}}

In [80]:
count_1 = 0
count_2 = 0
for i in range(len(c)):
    if c[i] == 1.:
        count_1 = count_1+1
    elif c[i] == 2.:
        count_2 = count_2+1
        

In [122]:
np.squeeze(classes)

array([1., 1., 1., 1., 2., 2., 2., 2., 1., 2., 2., 1., 1., 2., 2., 1., 2.,
       1., 1., 2., 1., 2., 2., 1., 2., 2., 2., 2., 2., 2., 1., 2., 1., 2.,
       1., 1., 2., 2., 2., 2., 2., 2., 2., 1., 1., 2., 2., 2., 1., 1., 1.,
       2., 1., 2., 2., 1., 1., 2., 1., 2., 2., 1., 2., 2., 1., 2., 2., 2.,
       1., 2., 2., 1., 2., 1., 2., 2., 2., 1., 1., 1., 2., 2., 2., 1., 1.,
       2., 1., 1., 1., 1., 1., 2., 1., 2., 1., 1., 1., 2., 2., 1., 2., 2.,
       1., 1., 1., 1., 2., 2., 1., 2., 1., 1., 1., 2., 2., 1., 2., 1., 1.,
       2., 1., 2., 2., 2., 2., 2., 1., 2., 2., 2., 2., 2., 2., 2., 1., 2.,
       1., 2., 1., 2., 2., 2., 1., 2., 2., 1., 2., 2., 2., 2., 1., 2., 2.,
       2., 2., 2., 1., 2., 1., 2., 2., 1., 1., 2., 2., 2., 1., 2., 2., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [115]:
scores.flatten()

array([9.8826128e-01, 9.8801851e-01, 8.8748783e-01, 2.0485505e-01,
       4.8549697e-02, 1.8125683e-02, 8.7946160e-03, 1.7828522e-04,
       1.2670735e-04, 8.8133223e-05, 5.4059219e-05, 4.5420398e-05,
       1.9386347e-05, 1.5012545e-05, 1.0228662e-05, 4.5813645e-06,
       2.5409140e-06, 1.7023957e-06, 1.5871854e-06, 1.0515998e-06,
       8.3231561e-07, 6.8115861e-07, 6.6189762e-07, 6.3813002e-07,
       6.3160303e-07, 4.4798924e-07, 4.3226180e-07, 3.9838571e-07,
       3.2695067e-07, 3.0226812e-07, 2.8255948e-07, 2.5347825e-07,
       2.5135535e-07, 2.1521490e-07, 1.8404036e-07, 1.8063265e-07,
       1.4873538e-07, 1.2843955e-07, 1.0151435e-07, 9.2066713e-08,
       8.5127006e-08, 7.6968647e-08, 5.5803586e-08, 5.3804154e-08,
       5.1538272e-08, 4.9754547e-08, 4.1262446e-08, 3.9057706e-08,
       3.7031111e-08, 3.4948119e-08, 3.4280532e-08, 3.1269924e-08,
       2.1418925e-08, 2.0625192e-08, 1.8492429e-08, 1.6017545e-08,
       1.4999010e-08, 1.4476167e-08, 1.3919550e-08, 1.3570081e

In [140]:
vis_util.visualize_boxes_and_labels_on_image_array(image,
        np.squeeze(boxes),
        np.squeeze(classes).astype(np.int32),
        np.squeeze(scores),
        category_index,
        use_normalized_coordinates=True,
        line_thickness=8,
        min_score_thresh=0.05)
    #  cv2.putText(image, text, org, font, fontScale, 
    #   color, thickness, cv2.LINE_AA, False)
    #     cv2.putText(image, "ALERT",(0, 180),cv2.FONT_HERSHEY_SIMPLEX, 2, (0, 0,255), 2)
    #     playsound(r"alert.wav")
cv2.imshow('Object detector', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [151]:
sc = scores.flatten()
index = []
for i in range(len(sc)):
    if sc[i] > 0.05:
        index.append(i)

In [154]:
index

[0, 1, 2, 3]

In [155]:
for ind in index:
    print(ind)

0
1
2
3


In [156]:
for ind in index:
    
    try:
        if c[ind] ==1:

            vis_util.visualize_boxes_and_labels_on_image_array(image,
            np.squeeze(boxes),
            np.squeeze(classes).astype(np.int32),
            np.squeeze(scores),
            category_index,
            use_normalized_coordinates=True,
            line_thickness=8,
            min_score_thresh=0.75)
            cv2.imshow('Object detector', image)
            cv2.waitKey(0)
            cv2.destroyAllWindows()

        elif c[ind] ==2:

            vis_util.visualize_boxes_and_labels_on_image_array(image,
            np.squeeze(boxes),
            np.squeeze(classes).astype(np.int32),
            np.squeeze(scores),
            category_index,
            use_normalized_coordinates=True,
            line_thickness=8,
            min_score_thresh=0.75)
            cv2.putText(image, "ALERT",(0, 180),cv2.FONT_HERSHEY_SIMPLEX, 2, (0, 0,255), 2)
            playsound(r"alert.wav")
            cv2.imshow('Object detector', image)
            cv2.waitKey(0)
            cv2.destroyAllWindows()

        else:
            print("Here, There is no detection retaled to mask or not mask")
            
    except exception as e:
        
        print("Errors")
        

In [123]:
if c[ind]==2:
    vis_util.visualize_boxes_and_labels_on_image_array(image,
    np.squeeze(boxes),
    np.squeeze(classes).astype(np.int32),
    np.squeeze(scores),
    category_index,
    use_normalized_coordinates=True,
    line_thickness=8,
    min_score_thresh=0.75)
#  cv2.putText(image, text, org, font, fontScale, 
#   color, thickness, cv2.LINE_AA, False)
    cv2.putText(image, "ALERT",(0, 180),cv2.FONT_HERSHEY_SIMPLEX, 2, (0, 0,255), 2)
    playsound(r"alert.wav")
    cv2.imshow('Object detector', image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

    
    print("This man not wearing the mask")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [82]:
# if count_1 > count_2:
#     vis_util.visualize_boxes_and_labels_on_image_array(
#         image,
#         np.squeeze(boxes),
#         np.squeeze(classes).astype(np.int32),
#         np.squeeze(scores),
#         category_index,
#         use_normalized_coordinates=True,
#         line_thickness=8,
#         min_score_thresh=0.75)
#     cv2.imshow('Object detector', image)
#     #cv2.imwrite("mask_detection",image)
#     cv2.waitKey(0)
#     cv2.destroyAllWindows()
    
#if count_1 < count_2:

vis_util.visualize_boxes_and_labels_on_image_array(image,
    np.squeeze(boxes),
    np.squeeze(classes).astype(np.int32),
    np.squeeze(scores),
    category_index,
    use_normalized_coordinates=True,
    line_thickness=8,
    min_score_thresh=0.75)
#         cv2.putText(image, text, org, font, fontScale, 
#                  color, thickness, cv2.LINE_AA, False)

cv2.putText(image, "ALERT",(0, 180),cv2.FONT_HERSHEY_SIMPLEX, 0.85, (0, 0,255), 2)
playsound(r"alert.wav")
cv2.imshow('Object detector', image)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [32]:
print(count_1)

200


In [33]:
print(count_2)

100


In [17]:
from playsound import playsound

In [15]:
vis_util.visualize_boxes_and_labels_on_image_array(
image,
np.squeeze(boxes),
np.squeeze(classes).astype(np.int32),
np.squeeze(scores),
category_index,
use_normalized_coordinates=True,
line_thickness=8,
min_score_thresh=0.75)
#         cv2.putText(image, text, org, font, fontScale, 
#                  color, thickness, cv2.LINE_AA, False)
#cv2.putText(image, "ALERT",(0, 180),cv2.FONT_HERSHEY_SIMPLEX, 0.85, (0, 0,255), 2)
#playsound(r"C:\Users\ragav\OneDrive\Pictures\ineuron notes\face_\alert.wav")
#cv2.imshow('Object detector', image)
cv2.imwrite("mask_detection",image)
cv2.waitKey(0)
cv2.destroyAllWindows()

error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:661: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'cv::imwrite_'


In [45]:
s = scores.flatten()

In [46]:
s

array([9.8531950e-01, 9.6755624e-01, 7.6778764e-01, 7.0650077e-01,
       6.5854818e-02, 1.4508481e-02, 6.6859573e-03, 5.2119710e-04,
       1.3852218e-04, 8.8913162e-05, 4.5148936e-05, 1.5992538e-05,
       1.2889884e-05, 1.1196343e-05, 5.5309906e-06, 3.8919916e-06,
       3.4511359e-06, 2.5576521e-06, 2.2735542e-06, 1.2982332e-06,
       1.2198630e-06, 1.1041413e-06, 7.7285023e-07, 6.9100213e-07,
       6.6507420e-07, 5.4950766e-07, 4.4406468e-07, 4.3981109e-07,
       2.9679597e-07, 2.6218075e-07, 2.6005816e-07, 2.5327896e-07,
       2.4219119e-07, 2.3835821e-07, 2.0868258e-07, 1.8837214e-07,
       1.6968279e-07, 1.6018561e-07, 1.2754872e-07, 1.1981201e-07,
       1.1499616e-07, 7.3965261e-08, 6.6579304e-08, 6.2130269e-08,
       5.3277830e-08, 5.0393094e-08, 4.0113562e-08, 3.6026215e-08,
       3.3787639e-08, 3.3666701e-08, 3.1682667e-08, 3.0472350e-08,
       2.9701921e-08, 2.6981306e-08, 2.3298675e-08, 2.0578980e-08,
       1.9599968e-08, 1.8394424e-08, 1.6780225e-08, 1.5750940e

In [47]:
classes_flat = classes.flatten()

In [48]:
new_boxes = boxes.reshape(300, 4)

In [49]:
classes_flat2 = np.squeeze(classes).astype(np.int32)

In [50]:
classes_flat2

array([1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2,
       1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 2, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1,
       2, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2,
       1, 2, 2, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2,
       1, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [51]:
from playsound import playsound

In [52]:
for i in classes_flat2:
    if i == 1:
        vis_util.visualize_boxes_and_labels_on_image_array(
        image,
        np.squeeze(boxes),
        np.squeeze(classes).astype(np.int32),
        np.squeeze(scores),
        category_index,
        use_normalized_coordinates=True,
        line_thickness=8,
        min_score_thresh=0.75)
#         cv2.putText(image, text, org, font, fontScale, 
#                  color, thickness, cv2.LINE_AA, False)
        cv2.imshow('Object detector', image)
        cv2.waitKey(0)
        cv2.destroyAllWindows()

KeyboardInterrupt: 

In [40]:
category_index

{1: {'id': 1, 'name': 'with_mask'}, 2: {'id': 2, 'name': 'without_mask'}}

In [37]:
for i in classes_flat2:
    if i == 2:
        vis_util.visualize_boxes_and_labels_on_image_array(
        image,
        np.squeeze(boxes),
        np.squeeze(classes).astype(np.int32),
        np.squeeze(scores),
        category_index,
        use_normalized_coordinates=True,
        line_thickness=8,
        min_score_thresh=0.75)
#         cv2.putText(image, text, org, font, fontScale, 
#                  color, thickness, cv2.LINE_AA, False)
        cv2.putText(image, "ALERT",(0, 180),cv2.FONT_HERSHEY_SIMPLEX, 0.85, (0, 0,255), 2)
        playsound(r"C:\Users\ragav\OneDrive\Pictures\ineuron notes\face_\alert.wav")
        cv2.imshow('Object detector', image)
        cv2.waitKey(0)
        cv2.destroyAllWindows()

KeyboardInterrupt: 

In [ ]:
hjeeekjekjkjek

In [48]:
vis_util.visualize_boxes_and_labels_on_image_array(
        image,
        np.squeeze(boxes),
        np.squeeze(classes).astype(np.int32),
        np.squeeze(scores),
        category_index,
        use_normalized_coordinates=True,
        line_thickness=8,
        min_score_thresh=0.75)
    # All the results have been drawn on the frame, so it's time to display it.
cv2.imshow('Object detector', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
result = scores.flatten()
res = []
for idx in range(0, len(result)):
    if result[idx] > .40:
        res.append(idx)

In [53]:
k=np.squeeze(classes).astype(np.int32).flatten

In [54]:
k

<function ndarray.flatten>